Simplified float_int_args.c test.
TODO: FIX: This test (simplified or not) is still breaking on my machine. It breaks on the third argument (the second double number). It seems to always consider the first double argument.

/home/rodrigo/llvm/mctoll-patch/llvm/tools/llvm-mctoll/test/smoke_test/float_int_args.c:8:11: error: CHECK: expected string not found in input
// CHECK: 1.5
          ^
<stdin>:2:2: note: scanning from here
3
 ^
<stdin>:3:1: note: possible intended match here
0.5
^
...
<<<<<<
           1: 0.5 
           2: 3 
check:8'0      X error: no match found
           3: 0.5 
check:8'0     ~~~~
check:8'1     ?    possible intended match
>>>>>>